### ISSUE TITLE
Development Mode on Debian Linux fails to run

### ISSUE THREAD

**Issue by coolbikerdad** [bk1285/rpi_wordclock#121]
Hi. 

I am trying to understand the code before building my word clock (parts on order), and would like to build and run wordclock.py on Linux with GTK in development mode. Unfortunately, I cannot get the program to run. I have set an appropriate configuration file, fixed up font path issues, but the main error now seems to be that the colour values for GTK appear to be integers rather than tuples. In GTKstrip.py, line 105 I get an exception thrown: 
AttributeError: 'int' object has no attribute 'r'
and the list in self.colors is a list of integers, not Color objects.
Is there a Linux/GTK setup I can use to get the program running? I am on latest x86 Debian Stretch. I wonder if the GTK libraries have moved on since the program was written? Hads development mode been tested recently? Love what the software will do!

regards
Neil Matthew

**Comment by bk1285** [comment]
Dear Neil,

just verified, that it works on my PC, running Ubuntu 18.04.2 LTS.
@coolbikerdad: With "development mode", you're referring to the following configuration within rpi_wordclock/wordclock_config/wordclock_config.cfg, right?
```
[wordclock]
developer_mode = True
```
@mrksngl: Any idea?

Best,
Bernd

**Comment by andredatele** [comment]
I get this same error on both raspbian and also Ubuntu 18.04.2 LTS:

![GTK](https://user-images.githubusercontent.com/33327533/62651169-ae0f2700-b958-11e9-9aa4-a8652e9e3008.PNG)

**Comment by bk1285** [comment]
Reopen, if unresolved.
